{% set name = "hostess" %}
{% set version = "0.10.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/hostess-{{ version }}.tar.gz
  sha256: 463cf413f293e608b90fd1af0f101b6886e2bd3545b79caf3a4b8709f896a189

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python

requirements:
  host:
    - python >=3.10
    - pip
  run:
    - python >=3.10
    - boto3
    - cytoolz
    - dill
    - dustgoggles
    - fabric
    - fire
    - invoke
    - more-itertools
    - pandas
    - protobuf
    - psutil
    - pympler
    - python-magic
    - pyyaml
    - requests
    - rich
    - textual

test:
  imports:
    - hostess
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/MillionConcepts/hostess
  summary: intuitive admin library
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Sierra-MC
    - m-stclair
