{% set python_min = "3.10%"   %}
{% set name       = "hostess" %}
{% set version    = "0.11.0"  %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/hostess-{{ version }}.tar.gz
  sha256: ad8b820c0eac5c68b4e734b549b32237cdc962afb27e58b7bbbf68c1ddb94ad1

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python

requirements:
  host:
    - python >={{ python_min }}
    - pip
    - setuptools >=64
  run:
    - python >={{ python_min }}
    - boto3
    - cytoolz
    - dill
    - dustgoggles
    - fabric
    - fire
    - invoke
    - more-itertools
    - pandas
    - protobuf
    - psutil
    - pympler
    - python-magic
    - pyyaml
    - requests
    - rich
    - textual

test:
  imports:
    - hostess
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/MillionConcepts/hostess
  summary: intuitive admin library
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Sierra-MC
    - m-stclair
