{% set name = "hostess" %}
{% set version = "0.11.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/hostess-{{ version }}.tar.gz
  sha256: ad92d942e6395b4cb0e4abfc39e63ba6e51661354cc26aa384b2fae376ffd762

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python

requirements:
  host:
    - python >=3.10
    - pip
    - setuptools >=64
  run:
    - python >=3.10
    - boto3
    - cytoolz
    - dill
    - dustgoggles
    - fabric
    - fire
    - invoke
    - more-itertools
    - pandas
    - protobuf
    - psutil
    - pympler
    - python-magic
    - pyyaml
    - requests
    - rich
    - textual

test:
  imports:
    - hostess
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/MillionConcepts/hostess
  summary: intuitive admin library
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Sierra-MC
    - m-stclair
